name: Latest Pull Requests - Manual
on: workflow_dispatch

jobs:
  logLatestPR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Query Github API
        uses: octokit/graphql-action@v2.x
        id: get_latest_pr
        with:
          query: |
            query {
              search(query: "is:pr author:rpetit3 -user:rpetit3 -user:rpetit3-fun -user:staphopia -user:bactopia -user:Read-Lab-Confederation", type: ISSUE, first: 100) {
                issueCount
                edges {
                  node {
                  ... on PullRequest {
                      number
                      title
                      repository {
                        nameWithOwner
                      }
                      createdAt
                      mergedAt
                      url
                      changedFiles
                      additions
                      deletions
                    }
                  }
                }
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Query Github API
        uses: octokit/graphql-action@v2.x
        id: get_latest_pr_merged
        with:
          query: |
            query {
              search(query: "is:pr is:merged author:rpetit3 -user:rpetit3 -user:rpetit3-fun -user:staphopia -user:bactopia -user:Read-Lab-Confederation", type: ISSUE, first: 100) {
                issueCount
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update and Commit
        run: |
          echo ${{ github.ref }}
          echo '${{ steps.get_latest_pr.outputs.data }}'" > data/github.json
          echo '${{ steps.get_latest_pr_merged.outputs.data }}'" > data/merged.json
          git add data/github.json
          git add data/merged.json
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "ci: update github stats" -a | exit 0

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
